//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""d0ed0e4b-e3fc-4777-be6c-a879d2458f28"",
            ""actions"": [
                {
                    ""name"": ""RStickClick"",
                    ""type"": ""Button"",
                    ""id"": ""025f3d75-7181-4e97-8510-0af1bda38b9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LStickClick"",
                    ""type"": ""Button"",
                    ""id"": ""2ef08f4d-84a3-4701-aaee-4860f5ac6860"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AButtonR"",
                    ""type"": ""Button"",
                    ""id"": ""4bb6fc4a-44f0-4b42-8410-ef4fabb68b3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BButtonR"",
                    ""type"": ""Button"",
                    ""id"": ""ff3c5c60-a561-45fe-9f92-754c2cefc63b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XButtonR"",
                    ""type"": ""Button"",
                    ""id"": ""2a1c9010-b37b-4068-8378-f3a2fa93dfe0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YButtonR"",
                    ""type"": ""Button"",
                    ""id"": ""04c110df-0174-4c58-bbc3-0456ca4b3ba9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AButtonL"",
                    ""type"": ""Button"",
                    ""id"": ""744e2e54-d58e-430f-8d9b-e29712785f37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BButtonL"",
                    ""type"": ""Button"",
                    ""id"": ""048e7bae-9ca4-4b75-a0e2-dc730ac1b8c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XButtonL"",
                    ""type"": ""Button"",
                    ""id"": ""b6c3aa3a-8cac-4a0a-8854-b2ed9e799afd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YButtonL"",
                    ""type"": ""Button"",
                    ""id"": ""927642cf-684c-4066-ab19-aff4d221510f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartButton"",
                    ""type"": ""Button"",
                    ""id"": ""ed8ee23c-64ee-418f-875a-c2c2808b05e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectButton"",
                    ""type"": ""Button"",
                    ""id"": ""b4a39c0b-8c6a-4918-bb40-087c5bfffa3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RStickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""bab96483-a05b-4204-8fc7-8b698bb121e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LStickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""559587a4-0a8f-44c9-b6bb-2f12241e2630"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""bc4d555a-b58e-4841-93ef-a83602187701"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""caec6fde-df9f-4e63-a79e-76240ff20057"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RBumper"",
                    ""type"": ""Button"",
                    ""id"": ""1be29eb4-b1c3-4c2d-8cd4-9621f9d9395e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBumper"",
                    ""type"": ""Button"",
                    ""id"": ""248b973a-56d0-4527-a1f8-bd9ed142bbee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""add87313-966f-42a3-9238-d90a87c1036f"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStickClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb24a6d6-7dca-4fd7-b84d-142cff2dbe45"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f690e093-0ecb-4de4-a1cf-4a9d27deb3de"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AButtonR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ece8ab3-0af5-475a-b415-31d6e1b60be0"",
                    ""path"": ""<OculusTouchController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BButtonR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5a331a9-9cd0-41b0-bb53-72918b4e297d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XButtonR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ac03177-8fa4-42dc-a66f-965f6440e8d3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YButtonR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""948fc770-1c27-425c-87d1-9e4ccbe2c19f"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AButtonL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4920cdfd-fdf7-412c-aadd-08e080b66d6a"",
                    ""path"": ""<OculusTouchController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BButtonL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d0ebe6c-7d25-4e40-920f-8ca16d8a95e6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XButtonL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fe1db18-5e6e-47d6-989a-9616f4672524"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YButtonL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""188c40bf-160a-4bb2-8443-180d59c997ad"",
                    ""path"": ""<OculusTouchController>{LeftHand}/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86ce9a4a-8f7f-423f-ac78-c3d6a1610e97"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd0f0fbe-8d85-428a-a13b-5fbd4c71441b"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e55532ca-9bf8-488b-a41f-1efd8197161d"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66c83461-abdc-4e3f-97dc-8e12ee41a5f7"",
                    ""path"": ""<OculusTouchController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57390a91-bd88-4c2f-9114-0c664042a04d"",
                    ""path"": ""<OculusTouchController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acb19827-fa67-4eac-8f0e-f77420aa93d8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a90fd1e-0275-4273-b476-220c9e21441e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_RStickClick = m_Player.FindAction("RStickClick", throwIfNotFound: true);
        m_Player_LStickClick = m_Player.FindAction("LStickClick", throwIfNotFound: true);
        m_Player_AButtonR = m_Player.FindAction("AButtonR", throwIfNotFound: true);
        m_Player_BButtonR = m_Player.FindAction("BButtonR", throwIfNotFound: true);
        m_Player_XButtonR = m_Player.FindAction("XButtonR", throwIfNotFound: true);
        m_Player_YButtonR = m_Player.FindAction("YButtonR", throwIfNotFound: true);
        m_Player_AButtonL = m_Player.FindAction("AButtonL", throwIfNotFound: true);
        m_Player_BButtonL = m_Player.FindAction("BButtonL", throwIfNotFound: true);
        m_Player_XButtonL = m_Player.FindAction("XButtonL", throwIfNotFound: true);
        m_Player_YButtonL = m_Player.FindAction("YButtonL", throwIfNotFound: true);
        m_Player_StartButton = m_Player.FindAction("StartButton", throwIfNotFound: true);
        m_Player_SelectButton = m_Player.FindAction("SelectButton", throwIfNotFound: true);
        m_Player_RStickAxis = m_Player.FindAction("RStickAxis", throwIfNotFound: true);
        m_Player_LStickAxis = m_Player.FindAction("LStickAxis", throwIfNotFound: true);
        m_Player_RTrigger = m_Player.FindAction("RTrigger", throwIfNotFound: true);
        m_Player_LTrigger = m_Player.FindAction("LTrigger", throwIfNotFound: true);
        m_Player_RBumper = m_Player.FindAction("RBumper", throwIfNotFound: true);
        m_Player_LBumper = m_Player.FindAction("LBumper", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_RStickClick;
    private readonly InputAction m_Player_LStickClick;
    private readonly InputAction m_Player_AButtonR;
    private readonly InputAction m_Player_BButtonR;
    private readonly InputAction m_Player_XButtonR;
    private readonly InputAction m_Player_YButtonR;
    private readonly InputAction m_Player_AButtonL;
    private readonly InputAction m_Player_BButtonL;
    private readonly InputAction m_Player_XButtonL;
    private readonly InputAction m_Player_YButtonL;
    private readonly InputAction m_Player_StartButton;
    private readonly InputAction m_Player_SelectButton;
    private readonly InputAction m_Player_RStickAxis;
    private readonly InputAction m_Player_LStickAxis;
    private readonly InputAction m_Player_RTrigger;
    private readonly InputAction m_Player_LTrigger;
    private readonly InputAction m_Player_RBumper;
    private readonly InputAction m_Player_LBumper;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @RStickClick => m_Wrapper.m_Player_RStickClick;
        public InputAction @LStickClick => m_Wrapper.m_Player_LStickClick;
        public InputAction @AButtonR => m_Wrapper.m_Player_AButtonR;
        public InputAction @BButtonR => m_Wrapper.m_Player_BButtonR;
        public InputAction @XButtonR => m_Wrapper.m_Player_XButtonR;
        public InputAction @YButtonR => m_Wrapper.m_Player_YButtonR;
        public InputAction @AButtonL => m_Wrapper.m_Player_AButtonL;
        public InputAction @BButtonL => m_Wrapper.m_Player_BButtonL;
        public InputAction @XButtonL => m_Wrapper.m_Player_XButtonL;
        public InputAction @YButtonL => m_Wrapper.m_Player_YButtonL;
        public InputAction @StartButton => m_Wrapper.m_Player_StartButton;
        public InputAction @SelectButton => m_Wrapper.m_Player_SelectButton;
        public InputAction @RStickAxis => m_Wrapper.m_Player_RStickAxis;
        public InputAction @LStickAxis => m_Wrapper.m_Player_LStickAxis;
        public InputAction @RTrigger => m_Wrapper.m_Player_RTrigger;
        public InputAction @LTrigger => m_Wrapper.m_Player_LTrigger;
        public InputAction @RBumper => m_Wrapper.m_Player_RBumper;
        public InputAction @LBumper => m_Wrapper.m_Player_LBumper;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @RStickClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRStickClick;
                @RStickClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRStickClick;
                @RStickClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRStickClick;
                @LStickClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLStickClick;
                @LStickClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLStickClick;
                @LStickClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLStickClick;
                @AButtonR.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButtonR;
                @AButtonR.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButtonR;
                @AButtonR.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButtonR;
                @BButtonR.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButtonR;
                @BButtonR.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButtonR;
                @BButtonR.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButtonR;
                @XButtonR.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButtonR;
                @XButtonR.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButtonR;
                @XButtonR.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButtonR;
                @YButtonR.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButtonR;
                @YButtonR.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButtonR;
                @YButtonR.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButtonR;
                @AButtonL.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButtonL;
                @AButtonL.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButtonL;
                @AButtonL.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAButtonL;
                @BButtonL.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButtonL;
                @BButtonL.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButtonL;
                @BButtonL.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBButtonL;
                @XButtonL.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButtonL;
                @XButtonL.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButtonL;
                @XButtonL.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnXButtonL;
                @YButtonL.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButtonL;
                @YButtonL.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButtonL;
                @YButtonL.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnYButtonL;
                @StartButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStartButton;
                @StartButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStartButton;
                @StartButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStartButton;
                @SelectButton.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectButton;
                @SelectButton.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectButton;
                @SelectButton.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectButton;
                @RStickAxis.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRStickAxis;
                @RStickAxis.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRStickAxis;
                @RStickAxis.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRStickAxis;
                @LStickAxis.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLStickAxis;
                @LStickAxis.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLStickAxis;
                @LStickAxis.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLStickAxis;
                @RTrigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRTrigger;
                @RTrigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRTrigger;
                @RTrigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRTrigger;
                @LTrigger.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLTrigger;
                @LTrigger.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLTrigger;
                @LTrigger.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLTrigger;
                @RBumper.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRBumper;
                @RBumper.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRBumper;
                @RBumper.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRBumper;
                @LBumper.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLBumper;
                @LBumper.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLBumper;
                @LBumper.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLBumper;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RStickClick.started += instance.OnRStickClick;
                @RStickClick.performed += instance.OnRStickClick;
                @RStickClick.canceled += instance.OnRStickClick;
                @LStickClick.started += instance.OnLStickClick;
                @LStickClick.performed += instance.OnLStickClick;
                @LStickClick.canceled += instance.OnLStickClick;
                @AButtonR.started += instance.OnAButtonR;
                @AButtonR.performed += instance.OnAButtonR;
                @AButtonR.canceled += instance.OnAButtonR;
                @BButtonR.started += instance.OnBButtonR;
                @BButtonR.performed += instance.OnBButtonR;
                @BButtonR.canceled += instance.OnBButtonR;
                @XButtonR.started += instance.OnXButtonR;
                @XButtonR.performed += instance.OnXButtonR;
                @XButtonR.canceled += instance.OnXButtonR;
                @YButtonR.started += instance.OnYButtonR;
                @YButtonR.performed += instance.OnYButtonR;
                @YButtonR.canceled += instance.OnYButtonR;
                @AButtonL.started += instance.OnAButtonL;
                @AButtonL.performed += instance.OnAButtonL;
                @AButtonL.canceled += instance.OnAButtonL;
                @BButtonL.started += instance.OnBButtonL;
                @BButtonL.performed += instance.OnBButtonL;
                @BButtonL.canceled += instance.OnBButtonL;
                @XButtonL.started += instance.OnXButtonL;
                @XButtonL.performed += instance.OnXButtonL;
                @XButtonL.canceled += instance.OnXButtonL;
                @YButtonL.started += instance.OnYButtonL;
                @YButtonL.performed += instance.OnYButtonL;
                @YButtonL.canceled += instance.OnYButtonL;
                @StartButton.started += instance.OnStartButton;
                @StartButton.performed += instance.OnStartButton;
                @StartButton.canceled += instance.OnStartButton;
                @SelectButton.started += instance.OnSelectButton;
                @SelectButton.performed += instance.OnSelectButton;
                @SelectButton.canceled += instance.OnSelectButton;
                @RStickAxis.started += instance.OnRStickAxis;
                @RStickAxis.performed += instance.OnRStickAxis;
                @RStickAxis.canceled += instance.OnRStickAxis;
                @LStickAxis.started += instance.OnLStickAxis;
                @LStickAxis.performed += instance.OnLStickAxis;
                @LStickAxis.canceled += instance.OnLStickAxis;
                @RTrigger.started += instance.OnRTrigger;
                @RTrigger.performed += instance.OnRTrigger;
                @RTrigger.canceled += instance.OnRTrigger;
                @LTrigger.started += instance.OnLTrigger;
                @LTrigger.performed += instance.OnLTrigger;
                @LTrigger.canceled += instance.OnLTrigger;
                @RBumper.started += instance.OnRBumper;
                @RBumper.performed += instance.OnRBumper;
                @RBumper.canceled += instance.OnRBumper;
                @LBumper.started += instance.OnLBumper;
                @LBumper.performed += instance.OnLBumper;
                @LBumper.canceled += instance.OnLBumper;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnRStickClick(InputAction.CallbackContext context);
        void OnLStickClick(InputAction.CallbackContext context);
        void OnAButtonR(InputAction.CallbackContext context);
        void OnBButtonR(InputAction.CallbackContext context);
        void OnXButtonR(InputAction.CallbackContext context);
        void OnYButtonR(InputAction.CallbackContext context);
        void OnAButtonL(InputAction.CallbackContext context);
        void OnBButtonL(InputAction.CallbackContext context);
        void OnXButtonL(InputAction.CallbackContext context);
        void OnYButtonL(InputAction.CallbackContext context);
        void OnStartButton(InputAction.CallbackContext context);
        void OnSelectButton(InputAction.CallbackContext context);
        void OnRStickAxis(InputAction.CallbackContext context);
        void OnLStickAxis(InputAction.CallbackContext context);
        void OnRTrigger(InputAction.CallbackContext context);
        void OnLTrigger(InputAction.CallbackContext context);
        void OnRBumper(InputAction.CallbackContext context);
        void OnLBumper(InputAction.CallbackContext context);
    }
}
